<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>TerminalEmulator.Demo</RootNamespace>
    <AssemblyName>TerminalEmulator.Demo</AssemblyName>
    <Platforms>AnyCPU;x64</Platforms>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TerminalEmulator.Control\TerminalEmulator.Control.csproj" />
  </ItemGroup>

</Project>
